#pragma once

#include <stddef.h>
#include <stdint.h>

#define FLIPFORGE_BRIDGE_PRODUCT "Flipforge Bridge"
#define FLIPFORGE_BRIDGE_VERSION "0.1.3"
#define FLIPFORGE_BRIDGE_PROTOCOL_VERSION 1U
#define FLIPFORGE_BRIDGE_WEBSITE "https://flipfor.ge"

/*
 * Use the Devboard's dedicated CLI UART route so Expansion traffic remains
 * isolated from the UART0/GPIO43/GPIO44 USB-UART route. UART1 is wired to
 * Flipper LPUART.
 */
#define BRIDGE_UART_PORT 1
#define BRIDGE_UART_TX_GPIO 17
#define BRIDGE_UART_RX_GPIO 18

#define BRIDGE_TCP_PORT 4242U
#define BRIDGE_TCP_BACKLOG 2
#define BRIDGE_TCP_IO_TIMEOUT_MS 5000U
#define BRIDGE_CLIENT_IDLE_TIMEOUT_MS 30000U

#define BRIDGE_EXPANSION_INITIAL_BAUD 9600U
#define BRIDGE_EXPANSION_STARTUP_DELAY_MS 3000U
#define BRIDGE_EXPANSION_TIMEOUT_MS 250U
#define BRIDGE_EXPANSION_ACK_TIMEOUT_MS 200U
#define BRIDGE_EXPANSION_HEARTBEAT_MS 100U
#define BRIDGE_EXPANSION_BAUD_DEAD_TIME_MS 25U
#define BRIDGE_EXPANSION_DETECT_PULSE_MS 2U
#define BRIDGE_EXPANSION_MAX_DATA 64U
#define BRIDGE_EXPANSION_MAX_RETRIES 3U
#define BRIDGE_EXPANSION_RETRY_BASE_MS 250U

#define BRIDGE_RPC_RX_BUFFER_BYTES 8192U
#define BRIDGE_TCP_READ_BYTES 1024U
#define BRIDGE_MANAGEMENT_MAX_PAYLOAD 512U
#define BRIDGE_MANAGEMENT_HEADER_SIZE 14U

#define BRIDGE_NONCE_BYTES 32U
#define BRIDGE_SESSION_ID_BYTES 8U
#define BRIDGE_PAIRING_SECRET_BYTES 32U
#define BRIDGE_HMAC_BYTES 32U
#define BRIDGE_AP_PASSWORD_BYTES 20U
#define BRIDGE_PAIRING_WINDOW_MS 120000U

#define BRIDGE_NVS_NAMESPACE "ffbridge"

extern const uint32_t bridge_preferred_baud_rates[];
extern const size_t bridge_preferred_baud_rate_count;
